algoritmo "Enquanto2"
// Função :
// Autor :
// Data : 11/20/2022
// Seção de Declarações 
var
   i:inteiro
inicio
      i <- 0
      
      enquanto i <= 100 faca
               escreval(i)
               i <- i + 1

               se i = 50 entao
                  escreval("o i vale 50")
                  interrompa
               fimse
               
      fimenquanto
      escreval("Fim")
      
fimalgoritmo
