algoritmo "EscolhaSe"
// Função :
// Autor :
// Data : 11/19/2022
// Seção de Declarações 
var
   voto:literal
inicio
      Escreval("Digite seu voto")
      leia(voto)
      
      se voto = "20" entao
         escreval("Você votou em Rafael Martins")
      senao
      se voto = "30" entao
         escreval("Você votou no Pernalonga")
      senao
      se voto = "40" entao
         escreval("Você votou no Patolino")
      senao
           escreval("Voto nulo.")
      fimse
      fimse
      fimse
      
fimalgoritmo

