algoritmo "EscolhaCaso"
// Função :
// Autor :
// Data : 11/19/2022
// Seção de Declarações
var
   voto : inteiro
inicio
      Escreval("Digite seu voto")
      leia(voto)

      Escolha voto
      
      caso > 20
         escreval("Você votou em Rafael Martins")

      caso > 30
         escreval("Você votou no Pernalonga")

      caso > 40
         escreval("Você votou no Patolino")

      outrocaso
           escreval("Voto nulo.")

      fimescolha

fimalgoritmo

