algoritmo "Menu"
// Função :
// Autor :
// Data : 11/20/2022
// Seção de Declarações 
var
   opcaoMenu : literal
   
inicio
      escreval("1 - Troca de óleo")
      escreval("2 - Balanceiamento")
      escreval("3 - Sair")
      leia(opcaoMenu)
      enquanto opcaoMenu <> "3" faca

            escreval("1 - Troca de óleo")
            escreval("2 - Balanceiamento")
            escreval("3 - Sair")
            leia(opcaoMenu)
      
      fimenquanto
fimalgoritmo
