algoritmo "Para5"
// Função :
// Autor :
// Data : 11/20/2022
// Seção de Declarações 
var
   i,aleatorioMaximo, aleatorioMinimo, incremento : inteiro
inicio

repita
aleatorio 1,100
          leia(aleatorioMaximo)
          leia(aleatorioMinimo)
aleatorio off
ate aleatorioMaximo >= aleatorioMinimo
limpatela

aleatorio 1,5
leia(incremento)
aleatorio off

para i de aleatorioMinimo ate aleatorioMaximo passo incremento faca
     escreval(i)
fimpara


fimalgoritmo
