algoritmo "Tabela Verdade"
// Função :
// Autor :
// Data : 11/19/2022
// Seção de Declarações 
var
  afirmacao: logico
  i, j: inteiro
inicio
      i: <- 10
      j: <- 20
         // sim E nao = não
         // sim E sim = sim
         // não E não = não
      
         // sim OU sim = sim
         // não ou não = sim
         // sim ou não = sim
         
      se (i = 10) e (j = 20) entao
            Escreval("Fazer algo")
      senao
            Escreval("Não fazer nada")
      fimse
fimalgoritmo
