algoritmo "TiposDeDados2"
// Função :
// Autor :
// Data : 11/18/2022
// Seção de Declarações 
var
    numero1, numero2, soma, subtracao, multiplicacao, divsao: inteiro
    divisao : real
inicio
      Escreval("N1")
      leia(numero1)
      Escreval("N2")
      leia(numero2)
      soma <- numero1 + numero2
      subtracao <- numero1 - numero2
      multiplicacao <- numero1 * numero2
      divisao <- numero1 / numero2
fimalgoritmo
